import Navbar from "@/components/shared/Navbar";
import "./globals.css";
import Footer from "@/components/shared/Footer";
import Scrollup from "@/components/shared/Scrollup";

export const metadata = {
  title: "Butterfly-salon & spa",
  description: "Generated by safayet Nur",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="min-h-screen">
          {" "}
          <Scrollup />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
