import "./globals.css";
import Scrollup from "@/components/shared/Scrollup";
import Providers from "@/providers";
// import { Montserrat } from "next/font/google";
import Toaster from "@/components/shared/Toaster";
import CartProvider from "@/providers/CartProvider";

// const montserrat = Montserrat({
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
// });
export const metadata = {
  title: "Butterfly-salon & spa",
  description: "Generated by safayet Nur",
};
// className={montserrat.className}
export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {" "}
          <CartProvider>
            <div>
              <Scrollup />
              {children}
            </div>
          </CartProvider>
        </Providers>

        <Toaster />
      </body>
    </html>
  );
}
