import "./globals.css";
import Scrollup from "@/components/shared/Scrollup";

export const metadata = {
  title: "Butterfly-salon & spa",
  description: "Generated by safayet Nur",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen">
          {" "}
          <Scrollup />
          {children}
        </div>
      </body>
    </html>
  );
}
